# Generated by Django 6.0 on 2026-01-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0002_signin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signin',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
