# Generated by Django 6.0 on 2026-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0003_alter_registration_email_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signin',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
