# Generated by Django 6.0 on 2026-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0004_alter_registration_email_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.TextField()),
            ],
        ),
    ]
