# Generated by Django 6.0 on 2026-01-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0006_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GST_percentage', models.IntegerField()),
                ('Preset_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
