# Generated by Django 6.0 on 2026-02-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0008_customer_payment_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcus.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcus.product')),
            ],
        ),
    ]
