# Generated by Django 6.0 on 2026-02-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0009_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
