# Generated by Django 6.0 on 2026-03-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0011_alter_bill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qrcus.bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=20),
        ),
    ]
