# Generated by Django 6.0.3 on 2026-03-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0012_sale_bill_alter_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='items_summary',
            field=models.TextField(default=''),
        ),
    ]
