# Generated by Django 6.0.3 on 2026-03-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0013_bill_items_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
