# Generated by Django 6.0.3 on 2026-03-19 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcus', '0014_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qrcus.bill'),
        ),
    ]
